<?php

/**
 * @file
 * Hook Implementations for this module.
 */

// Include the API.
require_once 'chado_custom_search.api.inc';

/**
 * Implement hook_menu().
 */
function chado_custom_search_menu() {
  $items = [];

  // Retrieve all defined chado custom searches.
  $searches = get_all_chado_custom_searches();

  // For each defined search, create a menu item.
  foreach ($searches as $class_name => $info) {
    $path = $class_name::$menu['path'];
    $items[ $path ] = [
      'title' => $class_name::$title,
      'description' => t($class_name::$description),
      'page callback' => 'drupal_get_form',
      'page arguments' => ['chado_custom_search_form', $class_name],
      'access arguments' => $class_name::$permissions,
      'type' => MENU_CALLBACK,
    ];
  }

  return $items;
}

/**
 * Provides the search page for any chado custom search.
 *
 * NOTE: This form is dynamic based on the information
 * provided in the search class.
 *
 * @param array $form
 *   Drupal's default form array.
 * @param array $form_state
 *   The current state of the form.
 * @return array
 *   The fully defined form including filter options and results.
 */
function chado_custom_search_form($form, &$form_state) {

  // Instantiate the search class.
  $class = $form_state['build_info']['args'][0];
  $search = new $class;

  // Add CSS/JS as defined in the class. We do this here so that it can
  // be added to and/or altered in the form method.
  $form['#attached']['css'] = [];
  foreach ($search::$attached['css'] as $subpath) {
    $path = drupal_get_path('module', $search::$module) . '/' . $subpath;
    $form['#attached']['css'][] = $path;
  }
  $form['#attached']['js'] = [];
  foreach ($search::$attached['js'] as $subpath) {
    $path = drupal_get_path('module', $search::$module) . '/' . $subpath;
    $form['#attached']['js'][] = $path;
  }

  // Get the form based on the search class.
  $form = $search->form($form, $form_state);

  // If we have values then we need to query!
  $doQuery = FALSE;
  $values = [];
  if (isset($form_state['values']) && !empty($form_state['values'])) {
    $doQuery = TRUE;
    $values = $form_state['values'];
  }
  elseif ($search::$require_submit == FALSE) {
    $doQuery = TRUE;
  }

  if ($doQuery) {
    $search->setValues($values, TRUE);
    $results = $search->getResults();
    $search->formatResults($form, $results);
  }

  return $form;
}

/**
 * Submit for chado_custom_search_form().
 */
function chado_custom_search_form_submit(&$form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}
