<?php

/**
 * @file
 * Hook Implementations for this module.
 */

// Include the API.
require_once 'chado_custom_search.api.inc';

/**
 * Implement hook_menu().
 */
function chado_custom_search_menu() {
  $items = [];

  // Retrieve all defined chado custom searches.
  $searches = get_all_chado_custom_searches();

  // For each defined search, create a menu item.
  foreach ($searches as $class_name => $info) {
    $path = $class_name::$menu['path'];
    $items[ $path ] = [
      'title' => $class_name::$title,
      'description' => t($class_name::$description),
      'page callback' => 'drupal_get_form',
      'page arguments' => ['chado_custom_search_form', $class_name],
      'access arguments' => $class_name::$permissions,
      'type' => MENU_CALLBACK,
    ];
  }

  return $items;
}

/**
 * Provides the search page for any chado custom search.
 *
 * NOTE: This form is dynamic based on the information
 * provided in hook_ccsearch_info().
 *
 * @param array $form
 *   Drupal's default form array.
 * @param array $form_state
 *   The current state of the form.
 * @return array
 *   The fully defined form including filter options and results.
 */
function chado_custom_search_form($form, $form_state) {
  // @debug dpm($form_state, 'form state');

  $class_name = $form_state['build_info']['args'][0];
  // @debug dpm($info, 'info');

  $search = new $class_name;
  $form = $search->form($form, $form_state);

  return $form;
}
